[project]
name = "apt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gdown>=5.2.0",
    "kaggle>=1.7.4.5",
    "loguru>=0.7.3",
    "matplotlib>=3.0.0",
    "openai-clip>=1.0.1",
    "opencv-python>=4.12.0.88",
    "rich>=14.2.0",
    "scikit-learn>=1.0.0",
    "scipy>=1.18.0",
    "seaborn>=0.13.2",
    "thop>=0.1.1.post2209072238",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "transformers>=4.57.1",
    "umap-learn>=0.5.9.post2",
    "wrapt>=2.3.0",
]
